# Esercitazione 4 Marzo 2025

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math
import time

## Esercizio 1
- Costruire due array numpy-array 2d di dimensione 5000x5000 i cui valori sono campionati da una distribuzione gaussiana con media 0 e varianza 1.
- Effetuare la somma tra le due matrici con due metodi:

        -  utilizzando le operazioni vettoriali 
        -  considerando due cicli espliciti annidati, su righe e colonne
- Confrontare le prestazioni in termini di tempo di esecuzione.
        


In [2]:
arr1 = np.random.randn(5000, 5000)
arr2 = np.random.randn(5000, 5000)
start = time.time()
res_vet = arr1 + arr2
print("Somma vettoriale [s]:", time.time() - start)
start = time.time()
res_loop = np.zeros_like(arr1)
for i in range(arr1.shape[0]):
    for j in range(arr1.shape[1]):
        res_loop[i][j] = arr1[i][j] + arr2[i][j]
print("Somma loop [s]:", time.time() - start)

Somma vettoriale [s]: 0.9053356647491455
Somma loop [s]: 16.55224347114563


## Esercizio 2
-      Costruire il numpy array  s  formato da 40 valori equidistanti in  [0,20],
-      considerarne il reshape in un array 2d che ha 4 righe con un numero opportuno di colonne e dire se il reshape crea una vista o una copia

In [15]:
s = np.linspace(0, 20, 40)
r = s.reshape((4, -1))
print("reshape:", r)
np.shares_memory(s, r) # true, quindi è una vista

reshape: [[ 0.          0.51282051  1.02564103  1.53846154  2.05128205  2.56410256
   3.07692308  3.58974359  4.1025641   4.61538462]
 [ 5.12820513  5.64102564  6.15384615  6.66666667  7.17948718  7.69230769
   8.20512821  8.71794872  9.23076923  9.74358974]
 [10.25641026 10.76923077 11.28205128 11.79487179 12.30769231 12.82051282
  13.33333333 13.84615385 14.35897436 14.87179487]
 [15.38461538 15.8974359  16.41025641 16.92307692 17.43589744 17.94871795
  18.46153846 18.97435897 19.48717949 20.        ]]


True

## Esercizio 3
-     Costruire il numpy array t formato da 100 valori equidistanti in  [0,4]
-     considerarne il reshape in un array 2d che ha 4 colonne con un numero opportuno di righe

In [4]:
t = np.linspace(0, 5, 100)
r = t.reshape((4, -1))
print("reshape:", r)

reshape: [[0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
  0.3030303  0.35353535 0.4040404  0.45454545 0.50505051 0.55555556
  0.60606061 0.65656566 0.70707071 0.75757576 0.80808081 0.85858586
  0.90909091 0.95959596 1.01010101 1.06060606 1.11111111 1.16161616
  1.21212121]
 [1.26262626 1.31313131 1.36363636 1.41414141 1.46464646 1.51515152
  1.56565657 1.61616162 1.66666667 1.71717172 1.76767677 1.81818182
  1.86868687 1.91919192 1.96969697 2.02020202 2.07070707 2.12121212
  2.17171717 2.22222222 2.27272727 2.32323232 2.37373737 2.42424242
  2.47474747]
 [2.52525253 2.57575758 2.62626263 2.67676768 2.72727273 2.77777778
  2.82828283 2.87878788 2.92929293 2.97979798 3.03030303 3.08080808
  3.13131313 3.18181818 3.23232323 3.28282828 3.33333333 3.38383838
  3.43434343 3.48484848 3.53535354 3.58585859 3.63636364 3.68686869
  3.73737374]
 [3.78787879 3.83838384 3.88888889 3.93939394 3.98989899 4.04040404
  4.09090909 4.14141414 4.19191919 4.24242424 4.29292929 4.343434

## Esercizio 4
Costruire il numpy array 1d C  di valori che variano tra 15 e 41 con step 2

-     Trasformarlo in un numpy array 2d con shape(7,2) usando il metodo . resize(7,2)  che lavora in-place,  (cioè  modifica l'array esistente).  

In [5]:
arr = np.arange(15, 42, 2)
print("arr:", arr)
arr.resize((7, 2))
print("arr:", arr)

arr: [15 17 19 21 23 25 27 29 31 33 35 37 39 41]
arr: [[15 17]
 [19 21]
 [23 25]
 [27 29]
 [31 33]
 [35 37]
 [39 41]]


 ## Esercizio 5
 Creare un array NumPy di 10 numeri interi casuali tra 1 e 100.
 

In [6]:
np.random.randint(1, 101, 10)

array([37, 50, 52, 91,  6, 86, 73, 10,  6, 50])

 ## Esercizio 6
 Eseguire uno shuffle degli elementi di un numpy-array di 30 numeri interi casuali tra 100 e 200.


In [7]:
arr = np.random.randint(100, 201, 30)
print("arr:", arr)
np.random.shuffle(arr)
print("arr:", arr)

arr: [156 131 161 100 182 136 108 183 176 111 167 118 110 125 148 158 140 168
 127 182 153 165 127 147 139 178 134 161 156 187]
arr: [156 161 108 153 100 148 127 182 167 161 176 110 134 140 156 183 187 158
 131 125 165 182 136 127 168 178 118 147 111 139]


  ## Esercizio 7
 Creare una permutazione casuale degli elementi di un numpy-array di 20 valori campionati da una distribuzione  gaussiana con media zero e varianza 1, senza modificarlo.

In [8]:
arr = np.random.randn(20)
print("arr:", arr)
np.random.shuffle(arr)
print("arr:", arr)

arr: [-0.56376868  1.04145301  0.12272748 -1.35108157  0.50885789 -0.32553304
  1.0600147  -0.28283554  0.37874167  1.11481842  2.36475852 -0.54945521
  0.66718577  0.50905059 -0.61911064  1.85364069  0.06757279 -1.13145833
 -2.22571159  0.01655933]
arr: [-0.61911064  1.0600147   0.06757279  1.11481842  2.36475852  0.12272748
 -0.56376868 -0.32553304 -0.28283554  1.85364069 -1.13145833 -2.22571159
 -0.54945521  0.01655933  0.50905059  0.37874167 -1.35108157  0.50885789
  1.04145301  0.66718577]


 ## Esercizio 8
-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo .ravel()  
-     Si tratta di una copia o di una vista?

In [16]:
A = np.arange(10, 19).reshape((3, 3))
r = A.ravel()
print("ravel:", r)
np.shares_memory(A, r) # true, quindi è una vista

ravel: [10 11 12 13 14 15 16 17 18]


True

## Esercizio 9
-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo  .flatten().
-     Si tratta di una copia o di una vista?

In [17]:
A = np.arange(10, 19).reshape((3, 3))
f = A.flatten()
print("flatten:", f)
np.shares_memory(A, f) # false, quindi è una copia

flatten: [10 11 12 13 14 15 16 17 18]


False

## Esercizio 10
- creare i due  numpy array 1d
    f1= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]  
    f2= [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
- "vederli" come matrici  4x4 ed effettuarne il prodotto scalare, memorizzando in f3 la matrice che nasce dal loro prodotto.

In [22]:
f1 = np.arange(0, 16)
f2 = np.arange(16, 32)
f3 = f1.reshape(4, 4) @ f2.reshape(4, 4)
print("f1:", f1)
print("f2:", f2)
print("f3:", f3)

f1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
f2: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
f3: [[ 152  158  164  170]
 [ 504  526  548  570]
 [ 856  894  932  970]
 [1208 1262 1316 1370]]


## Esercizio 11
Costruire:
 -     Numpy Array A di shape (2,10) : array di valori random campionati da una distribuzione gaussiana con media 0 e varianza 1.
 -     Numpy array 1D B di shape (20,) formato dagli interi da 0 a 19.
 
 "Vedere" A come un array 1D di 20 elementi ed effettuare la somma di A+B


In [23]:
A = np.random.randn(20).reshape(2, 10)
B = np.arange(0, 20)
print("A:", A)
print("B:", B)
print("A + B", A.ravel() + B)

A: [[ 0.21882143 -0.01921964  0.45263732 -0.42395004 -0.03855634 -0.88569549
  -0.69225932 -1.07372562  0.5364003  -0.68532918]
 [-0.1217307  -1.94403632  0.0265     -0.62270865 -0.28432317 -1.07850911
  -1.56852032 -0.27282048 -0.83036434 -0.30485888]]
B: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
A + B [ 0.21882143  0.98078036  2.45263732  2.57604996  3.96144366  4.11430451
  5.30774068  5.92627438  8.5364003   8.31467082  9.8782693   9.05596368
 12.0265     12.37729135 13.71567683 13.92149089 14.43147968 16.72717952
 17.16963566 18.69514112]


## Esercizio 12
-     Costruire f, un numpy array 1D , di shape (10,) costituito da 10 valori equidistanti nell'intervallo [0,1]
-     aumentarne la dimensionalità, in maniera tale che abbia shape (10,1)

In [27]:
f = np.linspace(0, 1, 10)
print("f:", f)
f.resize((10, 1))
print("f:", f)

f: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
f: [[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [0.44444444]
 [0.55555556]
 [0.66666667]
 [0.77777778]
 [0.88888889]
 [1.        ]]


## Esercizio 13
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12]])

  Costruire il numpy array che si ottiene concatenando a e b per righe

In [33]:
a = np.arange(14, 10, -1)

## Esercizio 14
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])

-
- Costruire il numpy array che si ottiene concatenando a e b per colonne

## Esercizio 15
Costruire, facendo uso di una sola riga di codice, la matrice A di ordine 10, che ha gli unici elementi diversi da zero, sulla diagonale principale, sulla codiagonale inferiore e sulla codiagonale superiore:

elementi diagonali $A_{i,i}=10 \quad$, i=1,20

elementi nella codiagonale inferiore $A_{i-1,i}=-12, \quad$ i=2,..,20, 

elementi nella codiagonale superiore $A_{i,i+1}=-2 \quad$ i=1,..,19

## Esercizio 16
Costruire la matrice identità, denominata *I*,  della stessa dimensione di *A*

## Esercizio 17
Facendo uso dell'operatore slicing *:* ,costruire la matrice AA selezionando dalla matrice A le righe che vanno dalla 2 alla 9 con step 2 e le colonne che vanno dalla 3 alla 6 con step 2.
La matrice AA è una vista o una copia?

## Esercizio 18
Facendo uso dell'operatore slicing *:*, costruire la matrice A1 selezionando dalla matrice A le colonne che vanno dalla 1 alla 5 con step 2.  Trasforma la matrice A1 in una copia.

## Esercizio 19

Costruisci due numpy array A e B di shape (5,5) 
   - A formata da numeri interi casuali  nell'intervallo [1,20]
   - B formata da numeri interi casuali  nell'intervallo [1,6]
 
  Costruisci con una sola riga di codice le seguenti matrici
  
  C=A+B   dove  $\quad c_{ij}=a_{ij}+b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  D=A-B   dove  $\quad d_{ij}=a_{ij}-b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  E=A*B   dove  $\quad e_{ij}=a_{ij}*b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  F=A/B   dove  $\quad f_{ij}=a_{ij}/b_{ij} \quad i=0,..,n, \quad j=0,...,n$

## Esercizio 20
Dato array NumPy che rappresenta le vendite giornaliere di un negozio per un mese,
vendite = np.random.randint(50, 200, 30) 

        Trova tutti i giorni in cui le vendite sono state superiori a 150.

        Calcola la media delle vendite solo per i giorni in cui sono state superiori a 150.

        Imposta le vendite a 0 per tutti i giorni in cui sono state inferiori a 100.


## Esercizio 21
Costruisci A, un numpy array 2d di shape (3,3) e b,  un numpy array 2d di shape (3,1)
e somma b ad ogni colonna di A b


# Esercizio 22
dato il numpy array 2d G=np.linspace(0,10,20).reshape(-1,4), scambia in G la seconda riga con la quarta riga

## Esercizio 23
Visualizzare il grafico della funzione $f(x)=sin^2(x)/x$ in 200 punti equidistanti nell'intervallo $[0.1,2\pi]$

## Esercizio 24

Data il numpy arra2d ottenuto facendo un reshape a (4,4) di un numpy array 1d di 16 valori equidistanti nell'intervallo [0,4]
ed un numpy array 1d di 4 valori  interi casuali nell'intervallo [10,60], costruire il prodotto scalare A per b,
usando A@b, e vettorizzando solo il ciclo interno.


## Esercizio 25
Dato g un numpy array 2d, estendilo di una riga in alto ed di una riga in basso, di una colonna a sinistra ed di una colonna a destra, usa la funzione g_est= np.pad(g,(1,1),mode='reflect'). Visualizza 'g_est' e commenta cosa vedi.

## Esercizio 26
Scrivi un programma Python che esegua l'elaborazione di un'immagine utilizzando un filtro di media. 

Utilizza il padding per gestire i pixel del bordo durante l'applicazione del filtro.

Il programma deve seguire questi passaggi:

- Carica l'immagine: Carica l'immagine 'cameraman.png' utilizzando la libreria Matplotlib.**image=plt.imread('cameraman.png')**
- Visualizza l'immagine originale **plt.imshow(image,cmap='gray')**
- definisce la dimensione del filtro, dim_filtro
- Applica il padding: Applica un padding costante di dim_filtro//2 pixel a tutti i bordi dell'immagine (utilizzando il metodo di numpy **image_bordered=np.pad(image,(dim_filtro//2,dim_filtro//2),, mode='reflect')**
- Crea il filtro di media: Crea un filtro di media di dimensioni *dim_filtroxdim_filtro*, dove tutti gli elementi sono pari a 1/(dim_filtroxdim_filtro)
- Applica il filtro: Scorri ogni pixel dell'immagine con padding (escludendo i bordi aggiunti) e applica il filtro di media.

   *Per ogni pixel, calcola la somma dei prodotti tra i pixel della sottomatrice dim_filtroxdim_filtro centrata sul pixel corrente e il filtro.*
   
- Crea l'immagine filtrata: Crea un nuovo array NumPy che rappresenta l'immagine filtrata, dove ogni pixel contiene il risultato dell'applicazione del filtro.
- Visualizza l'immagine filtrata: Visualizza l'immagine filtrata utilizzando Matplotlib con la mappa di colori 'gray'.
- Aggiungi una colorbar per visualizzare la scala dei valori dell'immagine filtrata.
- Mostra l'immagine filtrata con Matplotlib.


Requisiti:

-  Utilizzare la libreria Matplotlib per caricare e visualizzare l'immagine.
-  Utilizzare la libreria NumPy per la manipolazione degli array e per il padding.